### ISSUE TITLE
256kb roms jump to 655kb, wont fit on ti-84+

### ISSUE THREAD

**Issue by SwitchKillEngaged** [calc84maniac/tiboyse#4]
I got this a long time ago and remember converting Zelda for my ti84, now the 512kb file jumps to over 1200kb making it impossible to fit like it used to. The TiCalc.org version is no different. Am I insane or did this game fit on ti84+ in the past somehow? Thanks

It's not supposed to be 1200kb!
edit: the file size on computer is not the same as on the calc.

**Comment by SwitchKillEngaged** [comment]
Here's your video titled "Game Boy Emulator for TI-84+ - Link's Awakening with full grayscale"
https://youtu.be/Yh2Ogyq5uLk 
Doesn't say SE. I'm 99% sure this used to be possible!

**Comment by Eeems** [comment]
[From the readme](https://github.com/calc84maniac/tiboyse#frequently-asked-questions):

> ##
> **Q.** Will xxxx ROM fit on my calculator?
> 
> **A.** If you have a Silver Edition, ROMs up to 1MB (1024KB) in size will fit. If you have a normal TI-84+, ROMs up to 256KB in size will fit.
> 
> Make sure to delete useless APPs from your calculator if needed.

**Comment by SwitchKillEngaged** [comment]
I'm aware of the Readme. 

Here's his video titled "Game Boy Emulator for TI-84+ - Link's Awakening with full grayscale"
https://youtu.be/Yh2Ogyq5uLk
Doesn't say SE. I'm 99% sure this used to be possible!

**Comment by SwitchKillEngaged** [comment]
> [From the readme](https://github.com/calc84maniac/tiboyse#frequently-asked-questions):
> 
> > **Q.** Will xxxx ROM fit on my calculator?
> > **A.** If you have a Silver Edition, ROMs up to 1MB (1024KB) in size will fit. If you have a normal TI-84+, ROMs up to 256KB in size will fit.
> > Make sure to delete useless APPs from your calculator if needed.

**Comment by SwitchKillEngaged** [comment]
> ROMs up to 256KB in size will fit.

Not a single 256kb rom fits as they are converted into 600kb+ files. That's why I'm pointing out this problem. 

Here's his video titled "Game Boy Emulator for TI-84+ - Link's Awakening with full grayscale"
https://youtu.be/Yh2Ogyq5uLk
Doesn't say SE.

**Comment by Eeems** [comment]
> ##
> **Q.** How big are the APPs?
> 
> **A.** Generally, take the size of the ROM and add 16KB (16384 bytes). Sometimes you might get lucky and have a smaller APP if there is a lot of empty space in the ROM.
> 
> Pay attention to the size displayed when `tiboyse_makeapp.exe` finishes.

It sounds like something is going wrong with your ROM conversion.

**Comment by SwitchKillEngaged** [comment]
> It sounds like something is going wrong with your ROM conversion.

Do you get a different result with 512kb roms?
Here's a short video of what I'm doing. 
https://streamable.com/ca3coa

**Comment by Eeems** [comment]
So the issue that you are reporting is that the size reported by the conversation doesn't match the size that windows reports? You'll find that the raw file size of the file on your computer doesn't match the size that it will take on the device. This is expected.

**Comment by SwitchKillEngaged** [comment]
Oh, okay, thank you.
